name: Package Group Transfer Tool

on: 
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install ps2exe
        shell: pwsh
        run: Install-Module -Name ps2exe -Force -Scope CurrentUser

      - name: Compile to Exe
        shell: pwsh
        run: Invoke-ps2exe -inputFile ./groupTransferTool.ps1 `
                            -outputFile ./dist/GroupTransferTool.exe `
                            -noConsole `
                            -title "Group Transfer Tool" `
                            -version "1.0.0.0" `
                            -verbose

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: GroupTransferTool
          path: dist/GroupTransferTool.exe

      - name: Attach to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: dist/GroupTransferTool.exe
        
